---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  buildMac:
    name: Build macOS
    runs-on: macos-13
    strategy:
      matrix:
        xcode: [ Xcode_15.2 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Install the Apple certificate and provisioning profile
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$APPLE_CERTIFICATE" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Check if Cert installed correctly
        run: security find-identity -v -p codesigning
 
      - name: Investigate available XCode versions
        run: ls -n /Applications/ | grep Xcode*
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: install qt 5
        run: brew install qt@5
      - name: install build environment
        run: scripts/darwin/install.sh
      - name: Build project
        run: scripts/darwin/build.sh
      - name: Archive artifact
        run: zip DLT-macOS.zip -r build/dist
      - name: Upload DLT artifact
        uses: actions/upload-artifact@v4
        with:
          name: DLT-Mac
          path: DLT-macOS.zip

  createRelease:
    name: Create release
    runs-on: ubuntu-20.04
    needs: [ buildMac ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Download DLT macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: DLT-Mac
      
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: Check pre-release
        run: |
          echo "tag=${{steps.tagger.outputs.tag}}"
          if [[ ${{ steps.tagger.outputs.tag }} == *alpha* || ${{ steps.tagger.outputs.tag }} == *beta* ]]
          then
             prerelease=true
          else
             prerelease=false
          fi
          echo "PRE_RELEASE=$prerelease" >> $GITHUB_ENV
          echo "prerelease=$prerelease"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.tagger.outputs.tag}}
          generate_release_notes: true
          prerelease: ${{ env.PRE_RELEASE }}
          name: ${{steps.tagger.outputs.tag}}
          files: |
            DLT-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
